# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: dd49ac4e126cc3205bf1e708d212a0a755d762b403fe08570d3ed682450bdeb3b385c7fca6b84af27248c2369b2debbbc0ca768fb5dd51ea1f318454ddd073b8

test:
  secret_key_base: ec9298ed3a3d750d0f7017cc04612fc90c22d38ec135c3ccc91f68a51024be058f73d730cb1fbdd6b4df861882bc5a28c925c8288fc0ba0999fbfbadade9e3c1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
